[package]
name = "doh-auth-proxy"
description = "DoH proxy with HTTP authorization of Bearer token"
version = "0.1.0"
authors = ["Jun K"]
homepage = "https://github.com/junkurihara/doh-auth-proxy"
repository = "https://github.com/junkurihara/doh-auth-proxy"
license = "MIT"
readme = "README.md"
categories = ["asynchronous", "network-programming", "command-line-utilities"]
keywords = ["dns", "https", "doh", "proxy", "authorization"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.3.2"
clap = "2.33.3"
env_logger = "0.9.0"
log = "0.4.14"
tokio = { version = "1.12.0", features = [
  "net",
  "rt-multi-thread",
  "parking_lot",
  "time",
  "sync",
] }
futures = "0.3.17"
reqwest = { version = "0.11.4", features = ["default", "trust-dns", "json"] }
url = "2.2.2"
trust-dns-resolver = "0.20.3"
anyhow = "1.0.44"
dotenv = "0.15.0"
serde_json = "1.0.68"
jwt-simple = "0.10.6"
p256 = { version = "0.9.0", features = ["jwk"] }
chrono = "0.4.19"
odoh-rs = "1.0.0-alpha.1"
rand = "0.8.4"
bytes = "1.1.0"
urlencoding = "2.1.0"

[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
