[package]
name = "doh-auth-proxy"
version = "0.1.0"
authors = ["JK"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.3.2"
clap = "2.33.3"
env_logger = "0.8"
log = "0.4"
tokio = { version = "1.6.0", features = [
  "net",
  "rt-multi-thread",
  "parking_lot",
  "time",
  "sync",
] }
reqwest = "0.11.4"
url = "2.2.2"
