[workspace]

members = ["proxy-bin", "proxy-lib", "legacy"]
exclude = ["legacy"]
resolver = "2"

[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
strip = true
