[package]
name = "doh-auth-proxy"
description = "DNS Proxy for DoH, ODoH and Mutualized ODoH with Authorization"
version = "0.1.5"
authors = ["Jun Kurihara"]
homepage = "https://github.com/junkurihara/doh-auth-proxy"
repository = "https://github.com/junkurihara/doh-auth-proxy"
license = "MIT"
readme = "README.md"
categories = [
  "asynchronous",
  "network-programming",
  "command-line-utilities",
  "web-programming::http-client",
]
keywords = [
  "dns",
  "https",
  "dns-over-https",
  "doh",
  "oblivious-dns-over-https",
  "odoh",
  "mutualized-odoh",
  "proxy",
  "authorization",
]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.3.3"
clap = { version = "4.1.4", default-features = false, features = [
  "std",
  "cargo",
  "wrap_help",
] }
env_logger = "0.10.0"
log = "0.4.17"
tokio = { version = "1.24.2", features = [
  "net",
  "rt-multi-thread",
  "parking_lot",
  "time",
  "sync",
  "macros",
] }
futures = "0.3.25"
reqwest = { version = "0.11.14", features = ["default", "trust-dns", "json"] }
url = "2.3.1"
trust-dns-proto = "0.22.0"
trust-dns-resolver = "0.22.0"
anyhow = "1.0.68"
dotenv = "0.15.0"
serde_json = "1.0.91"
jwt-simple = "0.11.3"
p256 = { version = "0.12.0", features = ["jwk", "pem"] }
chrono = "0.4.23"
odoh-rs = { git = "https://github.com/junkurihara/odoh-rs.git" }
rand = "0.8.5"
bytes = "1.3.0"
urlencoding = "2.1.2"
toml = { version = "0.6.0", default-features = false, features = ["parse"] }
serde = "1.0.152"
hashlink = "0.8.1"
cedarwood = "0.4.6"
regex = "1.7.1"
rustc-hash = "1.1.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5.0"

[dev-dependencies]
trust-dns-client = "0.22.0"

[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
strip = true
