[package]
name = "doh-auth-proxy"
version = "0.1.0"
authors = ["JK"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.3.2"
clap = "2.33.3"
env_logger = "0.9.0"
log = "0.4.14"
tokio = { version = "1.9.0", features = [
  "net",
  "rt-multi-thread",
  "parking_lot",
  "time",
  "sync",
] }
futures = "0.3.15"
reqwest = { version = "0.11.4", features = ["default", "trust-dns"] }
url = "2.2.2"
trust-dns-resolver = "0.20.3"
anyhow = "1.0.42"
