version: "3"
services:
  doh-proxy:
    image: jqtype/doh-auth-proxy:latest
    container_name: doh-auth-proxy
    ## Uncomment if you build by yourself
    # build:
    #  context: ./
    restart: unless-stopped
    env_file: .env
    ports:
      - 50053:53/udp
      - 50053:53/tcp
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./.env:/opt/doh-auth-proxy/etc/.env
      - ${LOG_DIR}:/var/log/doh-auth-proxy

  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   command: dnscrypt-server --interval 30
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
