##############################################
#                                            #
#        doh-auth-proxy configuration        #
#                                            #
##############################################

##################################
#         Global settings        #
##################################

listen_addresses = ['127.0.0.1:50053', '[::1]:50053']
