services:
  doh-proxy:
    image: jqtype/doh-auth-proxy:latest
    container_name: doh-auth-proxy
    ## Uncomment if you build by yourself
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    init: true
    restart: unless-stopped
    ports:
      - 50053:53/udp
      - 50053:53/tcp
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    env_file: .env
    environment:
      - LOG_LEVEL=debug # debug|info|warn|error
      - LOG_TO_FILE=true
      - HOST_USER=jun
      - HOST_UID=501
      - HOST_GID=501
      - ENABLE_QUERY_LOG=true
      # - ENABLE_JSON_QUERY_LOG=true
    volumes:
      # Plugin Directory
      - ./plugins:/modoh/plugins
      # Log Directory for the case of LOG_TO_FILE=true
      - ./log:/modoh/log

  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   command: dnscrypt-server --interval 30
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
